import Image from 'next/image';
import Link from 'next/link'

export default function Blog1({ currentBlog }) {
    return (
        <div>
            <h1 className="text-3xl font-bold mb-4">What is Fintech?</h1>
            <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', marginBottom: '20px' }}>
                <div className="blog-img" style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', height: '200px', width: '400px', overflow: 'hidden', position: 'relative' }}>
                    <Image
                        src={currentBlog.image && currentBlog.image}
                        alt={currentBlog.title}
                        height={200}
                        width={200}
                        style={{
                            width: '100%',
                            height: '100%',
                            objectFit: 'cover',
                            position: 'absolute',
                            top: 0,
                            left: 0
                        }}
                    />
                </div></div>
            <p className="mb-4">
                Fintech's are companies that rely primarily on technology and cloud services and less so on physical locations to provide financial services to customers.
            </p>
            <p className="mb-4">
                you’re almost more likely to see the inside of a bank branch in an old movie than you are in real life. But take a look at your phone: there are probably at least two money apps on your home screen maybe more. According to McKinsey research, this is just one sign of a&nbsp;
                <Link target='_blank' href="https://www.mckinsey.com/~/media/mckinsey/industries/financial%20services/our%20insights/on%20the%20cusp%20of%20the%20next%20payments%20era%20future%20opportunities%20for%20banks/on-the-cusp-of-the-next-payments-era-future-opportunities-for-banks.pdf?shouldindex=false">new era in payments</Link>.
                What’s one major development behind this shift? Short word, big concept: fintech. </p>
            <p className='mb-4'>Fintechs short for financial technology are <Link target='_blank' href={'https://www.mckinsey.com/industries/financial-services/our-insights/fintechs-a-new-paradigm-of-growth'}>companies</Link> that rely primarily on technology to conduct fundamental functions provided by financial services, affecting how users store, save, borrow, invest, move, pay, and protect money. Most fintechs were launched after 2000, have raised funding since 2010, and have not yet reached maturity.
                They make it not only possible but also easy to move money between accounts, people, countries, and organizations. There’s no typical <Link target='_blank' href={'https://bluswap.co/'}>fintech company:</Link> fintechs include start-ups, growth companies, banks, nonbank financial institutions, and even cross-sector firms. Examples range from peer-to-peer payment services such as Venmo and Zelle to automated portfolio managers and stock- or cryptocurrency-trading apps such as Robinhood and Coinbase.</p>
            <p className='mb-4'>Fintech came to prominence around 2010, primarily in the payments space. <Link target='_blank' href={'https://www.mckinsey.com/industries/financial-services/our-insights/the-future-of-payments-is-frictionless-now-more-than-ever'}>Square</Link>, for instance, which was founded in 2009, enabled small companies or sellers to accept credit cards via a mobile device. Today, fintech disruptions have expanded to every corner of finance even areas once assumed to be safe from digital threat.
                Fintech is spreading fast: in the United States, for example, almost <Link target='_blank' href={'https://www.mckinsey.com/industries/financial-services/our-insights/financial-services-unchained-the-ongoing-rise-of-open-financial-data'}>one in two consumers</Link> in 2021 used a fintech product primarily peer-to-peer payment products and nonbank money transfers. Fintechs also raised <Link target='_blank' href={'https://www.mckinsey.com/industries/financial-services/our-insights/fintechs-a-new-paradigm-of-growth'}>record capital</Link> in the second half of the 2010s: venture capital funding grew from $19.4 billion in 2015 to $33.3 billion in 2020.</p>
            <p className='mb-4'>But recently, the <Link target='_blank' href={'https://www.mckinsey.com/industries/financial-services/our-insights/the-2023-mckinsey-global-payments-report'}>luster has worn off a bit:</Link> in 2022, a market correction caused a slowdown in fintech’s explosive growth momentum.
                As a result, fintechs have had to adjust to lower valuations and decreased willingness on the part of venture capital firms to fund companies with low margins. Rather than sprinting toward the hockey stick of old, fintechs today are focused on <Link target='_blank' href={'https://www.mckinsey.com/industries/financial-services/our-insights/fintechs-a-new-paradigm-of-growth'}>sustainable, profitable growth</Link>.
                Banks, in response, have seized the opportunity, developing their own fintech-informed digital products and services. In the future, competition for client deposits and balances will likely intensify.</p>
            <p className='mb-4'>But before we look into the future, let’s first explore the past and present. What is fintech, what kinds of convenience does it offer, and where in the world is it being used? Read on to find out.</p>
            <h1 className='mb-4'>Where is the banking industry in its digitization journey?</h1>
            <p className='mb-4'>Banking is in its second era of digitization, according to McKinsey senior partner <Link target='_blank' href={'https://www.mckinsey.com/our-people/brian-ledbetter'}>Brian Ledbetter</Link>. Traditionally, banks were anchored on a customer service arrangement that relied on branches and call centers. He says, “If you needed something, you’d either ring on the phone or go into the branch and get it done. Then, with the advent of smartphones, we discovered that mobile and digital technology was the primary way to engage with customers. . . . And so we had a boom in apps and automated journeys, which banks hooked up to their existing systems.”</p>
            <p className='mb-4'>This has led to a problem of technical debt: When banks set up this first phase of digitization, they did so with the technology they had at the time. Over time, these older systems have become obsolete. This created an opportunity for more agile fintech companies to disrupt business as usual, offering customers less clunky, more convenient ways of doing business. Today, <Link target='_blank' href={'https://www.mckinsey.com/industries/financial-services/our-insights/banks-core-technology-conundrum-reaches-an-inflection-point'}>banks are at an upgrade point</Link> for both the front and back ends.
                And their institutional capacity may be a benefit when it comes to adopting and deploying solutions based on <Link target='_blank' href={'https://www.mckinsey.com/industries/financial-services/our-insights/been-there-doing-that-how-corporate-and-investment-banks-are-tackling-gen-ai'}>rapidly advancing new technologies</Link>.</p>
            <h2 className='mb-4'>Which three themes will shape the next chapter of fintech growth?</h2>
            <p className='mb-4'>According to our research, <Link target='_blank' href={'https://www.mckinsey.com/industries/financial-services/our-insights/fintechs-a-new-paradigm-of-growth'}>three trends</Link> will shape the next phase of fintech growth. First, fintechs will continue to benefit from the radical digital transformation of the banking industry and e-commerce growth around the world, particularly in developing countries. About 73 percent of the world’s interactions with banks now take place through digital channels. B2B firms are also demanding more fintech solutions than ever. To capitalize on the demand, fintechs will need to keep up with evolving regulations and ensure they have adequate resources to comply.</p>
            <p className='mb-4'>Second, despite short-term pressures, fintechs still have room to achieve further growth in an expanding financial-services ecosystem. McKinsey estimates that fintechs will grow at roughly three times the overall banking industry’s growth rate between 2022 and 2028. Emerging markets will fuel much of this growth, particularly in Africa, Asia–Pacific (excluding China), Latin America, and the Middle East.</p>
            <p className='mb-4'>Finally, some fintechs are proving more resilient during the current market correction than others. Companies in the growth stage (series C and beyond) showed the highest sensitivity to 2022’s downturn. Fintechs in the early and pre-seed stages were more resilient. Funding for B2B fintechs was more resilient than that for B2C ones. Banking as a service (BaaS) and embedded finance, and small and medium-size enterprises (SMEs) and corporate value-added services were the verticals least affected by the downturn.</p>
            <h2 className='mb-4'>Which technologies are shaping the future of fintech?</h2>
            <p className='mb-4'>Over the next few years, we predict that the following <Link target='_blank' href={'https://www.mckinsey.com/cn/our-insights/our-insights/seven-technologies-shaping-the-future-of-fintech'}>seven technologies</Link> will advance fintech development while shaping the competitive landscape of finance:</p>


            <ul className='list-disc pl-5 mb-4'>
                {/* <li><i>Artificial intelligence (AI) will propel massive value creation.</i> Banks and other financial institutions are poised to adopt an 
                <Link target='_blank' href={'https://www.mckinsey.com/featured-insights/mckinsey-explainers/what-is-ai'}>AI</Link>-first mindset that will better prepare them to fend off expanding technology firms. McKinsey estimates that generative AI technologies alone may add
                 <Link target='_blank' href={'https://www.mckinsey.com/capabilities/mckinsey-digital/our-insights/the-economic-potential-of-generative-ai-the-next-productivity-frontier'}>up to $4.4 trillion annually</Link> to the global economy.</li> */}
               <li className='mb-2'>
    <h4 style={{margin: 0}}><em>Artificial intelligence (AI) – will propel massive value creation.</em></h4>
        {/* <p> */}
      Banks and other financial institutions are poised to adopt an <Link target='_blank' href="https://www.mckinsey.com/featured-insights/mckinsey-explainers/what-is-ai">AI</Link>-first mindset that will better prepare them to fend off expanding technology firms. 
      McKinsey estimates that generative AI technologies alone may add <Link href="https://www.mckinsey.com/capabilities/mckinsey-digital/our-insights/the-economic-potential-of-generative-ai-the-next-productivity-frontier" target="_blank">
        up to $4.4 trillion annually</Link> to the global economy.
    {/* </p> */}
  </li>
                <li className='mb-2'><h4 style={{margin: 0}}><em>Blockchain.</em></h4> <Link target='_blank' href={'https://www.mckinsey.com/featured-insights/mckinsey-explainers/what-is-blockchain'}>Blockchain</Link> will disrupt established financial protocols by allowing the storage of financial transactions in multiple places at once. Technologies such as smart contracts, zero-knowledge proof (a way of proving you have a piece of information without revealing what the information is), and distributed data storage and exchange essential to existing fintech innovations such as digital wallets, digital assets, decentralized finance, and nonfungible tokens will continue to play a prominent role.</li>
                <li className='mb-2'><h4 style={{margin: 0}}><em>Cloud computing.</em></h4> McKinsey research indicates that by 2030, cloud technology will account for EBITDA (earnings before interest, tax, depreciation, and amortization) in excess of $1 trillion across the world’s top 500 companies. For financial-services companies, <Link target='_blank' href={'https://www.mckinsey.com/featured-insights/mckinsey-explainers/what-is-cloud-computing'}>cloud computing</Link> will increase efficiency and lower costs.</li>
                <li className='mb-2'><h4 style={{margin: 0}}><em>The Internet of Things (IoT).</em></h4> <Link target='_blank' href={'https://www.mckinsey.com/featured-insights/mckinsey-explainers/what-is-the-internet-of-things'}>IoT</Link> applications for the finance industry include perception and smart sensor systems, wireless communication networks, and application and operations support.</li>
                <li className='mb-2'><h4 style={{margin: 0}}><em>Open-source software, serverless architecture, and software as a service (SaaS).</em></h4> These three technologies have become must-haves for technology companies and traditional financial institutions launching <Link target='_blank' href={'https://finex.bluswap.co/#/register'}>new fintech businesses</Link>. They enable increased speed and scalability, both critical for new businesses competing in the winner-takes-all digital economy.</li>
                <li className='mb-2'><h4 style={{margin: 0}}><em>No- and low-code development platforms.</em></h4>These allow programmers and general users to develop applications through graphical user interfaces and configurations (such as drag-and-drop) instead of traditional computer programming.</li>
                <li className='mb-2'><h4 style={{margin: 0}}><em>Hyper-automation.</em></h4> Hyper-automation is the use of AI, deep learning, event-based software, and other technologies and tools to improve <Link target='_blank' href={'https://www.mckinsey.com/featured-insights/mckinsey-explainers/what-is-decision-making'}>decision-making</Link> efficiency and work automation.</li>
            </ul>

            <h3 className='mb-4'>How can fintechs shift toward sustainable growth? </h3>
            <p className='mb-4'>Fintechs today are operating in a new environment. They can no longer afford to focus on growth at any cost. Given new liquidity constraints, fintechs are emphasizing profitability, not just growth in customer adoption numbers or total revenues. In 2019, McKinsey conducted a study of the growth patterns and performance of the world’s 5,000 largest public companies over the preceding 15 years. Based on our analysis, we expect <Link target='_blank' href={'https://www.mckinsey.com/industries/financial-services/our-insights/fintechs-a-new-paradigm-of-growth'}>four pathways</Link> to deliver the most impact for fintechs:</p>
            <ul className='list-disc pl-5 mb-4'>
                <li><em>Cost discipline.</em> Control costs to withstand the new funding environment while remaining flexible, nimble, and compliant.</li>
                <li><em>Measured growth based on a stable core.</em> Ensure there is a strong and stable core business with a targeted and proven market fit before expanding.</li>
                <li><em>Programmatic M&A.</em> Pursue M&A strategically and establish mutually beneficial partnerships based on programmatic strategy rooted in value sharing (with incumbents and other fintechs).</li>
                <li><em>Keep the culture alive.</em> Maintain the <Link target='_blank' href={'https://www.mckinsey.com/featured-insights/mckinsey-explainers/what-is-agile'}>agility</Link>, <Link target='_blank' href={'https://www.mckinsey.com/featured-insights/mckinsey-explainers/what-is-innovation'}>innovation</Link>, and culture that have propelled disruption so far.</li>
            </ul>

            <h3 className='mb-4'>What is open financial data?</h3>
            <p className='mb-4'>Financial data is pretty self-explanatory. It’s records of what we spend, save, and borrow, from mortgage payments to what we paid for this morning’s latte. In the past, banks have been the keepers of our financial data, and the idea of sharing it with anyone probably made us a little uncomfortable. Now, some of that data is being shared with third parties. This is a trend called <Link target='_blank' href={'https://www.mckinsey.com/industries/financial-services/our-insights/financial-services-unchained-the-ongoing-rise-of-open-financial-data'}>open financial data</Link> or open banking.</p>
            <p className='mb-4'>Let’s make one thing clear: none of this happens without consumer consent. But when consumers do consent, they allow a new and growing set of actors—both financial and nonfinancial to access their accounts and data to offer new products and services based on what they might need. This movement is still in its infancy but has <Link target='_blank' href={'https://www.mckinsey.com/industries/financial-services/our-insights/financial-services-unchained-the-ongoing-rise-of-open-financial-data'}>big potential</Link> to reshape our bank accounts, credit cards, payments, mortgages, loans, and even insurance policies.</p>
            <p className='mb-4'>The adoption of new digital-banking habits, in part as a result of fintech disruptions, appears to have accelerated open banking.</p>

            <h3 className='mb-4'>What can incumbents do to prevent disruption from fintechs?</h3>
            <p className='mb-4'>Fintechs have successfully highlighted existing financial institutions’ weaknesses in digital user experiences as well as in operational efficiency. It almost doesn’t matter how much market share fintechs take from incumbents when they have so successfully <Link target='_blank' href={'https://www.mckinsey.com/industries/financial-services/our-insights/banking-matters/seven-ways-for-financial-institutions-to-react-to-financial-technology-companies'}>recast customer expectations</Link>. At this point, it’s imperative for incumbents to transform to meet the new reality informed by fintechs. Here are seven actions for incumbents to consider:</p>

            <ul className='list-disc pl-5 mb-4'>
                <li><em>Buy a fintech,</em> whether for its traction, technology, or talent. But success depends on post-acquisition integration.</li>
                <li><em>Partner with a fintech</em> to induce faster time to market and cost-efficient implementation.</li>
                <li><em>Invest in fintechs</em> to hedge against some of the potential threat of disruption.</li>
                <li><em>Transform to become more like a fintech.</em> <Link target='_blank' href={'https://www.mckinsey.com/featured-insights/mckinsey-explainers/what-is-digital-transformation'}>Transformation</Link> is necessary to compete with outside threats, fintech or otherwise.</li>
                <li><em>Build an internal fintech.</em> Increasingly, incumbents are building their own internal fintechs to self-disrupt areas of their business before others can disrupt them.</li>
                <li><em>Serve the fintechs.</em> A few financial institutions might find competitive advantage in BaaS, serving fintechs as well as retailers, telcos, and more.</li>
                <li><em>Ignore fintechs.</em> Ignoring competition is rarely the right choice, but some incumbents are built behind regulatory moats that are difficult to disrupt.</li>
            </ul>

            <p className='mb-4'>The right answer is probably a combination of the above, implemented after careful planning.</p>
            <h3 className='mb-4'>How is fintech changing the financial landscape of Africa?</h3>
            <p className='mb-4'>Kenya has one of the highest levels of fintech penetration in the world, propelled largely by the explosive success of one fintech: <Link target='_blank' href={'https://www.mckinsey.com/industries/financial-services/our-insights/driven-by-purpose-15-years-of-m-pesas-evolution'}>M-Pesa</Link>. Launched in 2007, M-Pesa made it easier for Kenyans and later, people in other countries to use their mobile phones to reliably and quickly pay one another. It was quickly adopted by most Kenyans.</p>
            <p className='mb-4'>Between 2020 and 2021, the number of tech start-ups in Africa tripled to about <Link target='_blank' href={'https://www.mckinsey.com/industries/financial-services/our-insights/fintech-in-africa-the-end-of-the-beginning'}>5,200 companies</Link> and just under half of these are fintechs. Cash is used in about 90 percent of transactions in Africa, which means there is huge room for growth. If the sector overall can reach similar levels of penetration to those seen in Kenya, we’ve estimated that African fintech revenues could reach <Link href={'https://www.mckinsey.com/industries/financial-services/our-insights/fintech-in-africa-the-end-of-the-beginning'} target='_blank'>eight times</Link> their 2022 value by 2025.</p>
            <p className='mb-4'>Looking ahead, we anticipate that the growth opportunity in African fintech will likely be concentrated in 11 key markets: Cameroon, Côte d’Ivoire, Egypt, Ghana, Kenya, Morocco, <Link target='_blank' href={'https://www.mckinsey.com/featured-insights/middle-east-and-africa/harnessing-nigerias-fintech-potential'}>Nigeria</Link>, Senegal, South Africa (home to the continent’s most mature banking system), Tanzania, and Uganda. Together, these markets account for 70 percent of Africa’s GDP and half its population.</p>
            <p className='mb-4'>Here are four challenges emerging African fintechs may face:</p>

            <ul className='list-disc pl-5 mb-4'>
                <li><em>Reaching scale and profitability.</em> The total addressable market (that is, the number of viable customers) for African fintechs may be limited by infrastructure constraints, including weak mobile and internet penetration, lack of internet coverage, and limited payment rails (the underlying infrastructure that facilitates transactions). Lower disposable income and lower customer loyalty may also make it harder for fintechs to scale.</li>
                <li><em>Navigating an uncertain regulatory environment.</em> Different countries evolve regulations at different paces. Generally, complex and variable regulations make it difficult for fintechs to ensure business continuity and compliance across markets.</li>
                <li><em>Managing scarcity.</em> Funding is slowing down for African fintechs after a record-breaking 2021. But fintechs can’t afford to slow down their progress, especially as incumbents begin catching up. This suggests African fintechs will have to tighten their belts to adjust to a new venture funding reality.</li>
                <li><em>Building robust corporate-governance foundations.</em> In a regulatory, socioeconomic, and political environment that can be uncertain and fragmented, a strong corporate-governance structure can provide stability, clarity, and direction, especially in times of difficulty. Strong corporate governance includes strong culture building, productive stakeholder engagement, and a clear talent strategy to build the organization’s capabilities.</li>
            </ul>

            <p className='mb-4'>We don’t predict the path ahead to be smooth. But if stakeholders can work together to build on the momentum of recent years, the prospects for African fintechs are good.</p>

            <h3 className='mb-4'>What’s the state of fintech in Europe? </h3>
            <p className='mb-4'>Fintech in Europe was <Link target='_blank' href={'https://www.mckinsey.com/industries/financial-services/our-insights/detour-an-altered-path-to-profit-for-european-fintechs'}>hit hard by COVID-19</Link> and the resulting economic uncertainty. But in the long term, fintechs continue to gain in strength and relevance for customers and the economy. In each of the seven largest European economies, as measured by GDP, at least one fintech ranks among the <Link target='_blank' href={'https://www.mckinsey.com/industries/financial-services/our-insights/europes-fintech-opportunity'}>top five banking institutions</Link>.</p>
            <p className='mb-4'>But fintech has not progressed in each European market at the same speed. There’s a wide divergence of maturity and performance among countries, with a substantial gap between the top one-third and the rest. Two countries in particular stand out for their superior fintech ecosystem performance: Sweden and the United Kingdom. If fintech ecosystems in all European countries were to perform as well as the best in the region, the upside would be substantial: the number of fintech jobs would grow to more than 364,000, the volume of funding would more than double to almost €150 billion, and valuations would balloon to almost €1 trillion.</p>
            <p className='mb-4'>Here are the ways in which fintechs can <Link target='_blank' href={'https://www.mckinsey.com/industries/financial-services/our-insights/europes-fintech-opportunity'}>benefit European stakeholders</Link>:</p>

            <ul className='list-disc pl-5 mb-4'>
                <li>The appeal of fintechs to European customers is that they offer superior service at lower costs. International transfers, for example, can cost just 10 percent of the rates charged by traditional banking service institutions.</li>
                <li>Fintechs are a catalyst for disruptive innovation and growth in the financial ecosystem as a whole. They are typically more agile and quicker than incumbents, which means they are able to launch new products and services much faster (average time to market for fintechs is as little as two months, compared with 12 months for incumbents).</li>
                <li>Fintechs are an important source of potential growth for the overall economy. As of 2022, fintechs have created approximately 134,000 jobs across Europe and represent a total valuation of almost €430 billion. That’s more than the combined market capitalization of Europe’s seven largest listed banks.</li>
            </ul>
            <p className='mb-4'>For the European financial system to achieve the potential made possible by fintech, stakeholders such as public institutions, incumbents, and fintech upstarts will need to combine their strengths by setting up appropriate enabling structures and mechanisms.</p>

            <h3 className='mb-4'>What’s the future of fintech in the Middle East, North Africa, and Pakistan?</h3>
            <p className='mb-4'>Fintech has boomed in the Middle East, North Africa, and Pakistan (MENAP) in recent years: investor backing increased by <Link target='_blank' href={'https://www.mckinsey.com/industries/financial-services/our-insights/fintech-in-menap-a-solid-foundation-for-growth'}>around 36 percent annually</Link> from 2017 to 2022.</p>
            <p className='mb-4'>Here are five types of fintech companies in MENAP:</p>
            <ul className='list-disc pl-5 mb-4'>
                <li><em>Homegrown fintech start-ups.</em> Local fintech start-ups are addressing not only payments, lending, insurtech, and investments but also additional consumer and business needs such as home buying, payment apps and wallets, and merchant payment solutions.</li>
                <li><em>International fintech firms.</em> Established international fintech firms have launched in MENAP, stimulating competition and helping promote customer adoption.</li>
                <li><em>Banks.</em>Leading banking incumbents have moved quickly to offer digital-only offerings. These include Weyay Bank, a digital, youth-oriented bank by National Bank of Kuwait; Liv, a digital lifestyle banking app from Emirates National Bank of Dubai; and others.</li>
                <li><em>Other nonbank financial institutions.</em> Established payment processors, exchanges, remittance services, and other traditional infrastructure providers have launched mobile apps and digital portals. In some cases, they have partnered with fintech start-ups.</li>
                <li><em>Cross-sector fintech firms.</em> Large companies with leading market share, especially in telecommunications, have progressed from mobile cash to broader offerings such as mobile wallets, mobile payments, and branchless banking services.</li>
            </ul>

            <p className='mb-4'>While 2022 brought with it a global drop in fintech valuations, we believe the market in MENAP is likely to continue growing. By 2025, we estimate that fintech revenue in MENAP could be up to $4.5 billion.</p>
            <p className='mb-4'>Realizing this potential is another story. For fintechs to continue to expand their roles in the daily lives of consumers and businesses in MENAP, they’ll need to invest capital, work with regulators, and cultivate talent and partnerships.</p>

            <h5 className='mb-4'>Note:</h5>
            <p className='mb-4'>The information presented in this blog post is based on research from [<strong>McKinsey & Company</strong>], available at [<Link href={'https://www.mckinsey.com/featured-insights/mckinsey-explainers/what-is-fintech'} target='_blank'>https://www.mckinsey.com/featured-insights/mckinsey-explainers/what-is-fintech]</Link>. We would like to express our gratitude to [<strong>McKinsey</strong>] for their valuable insights on [fintech]. To access the full content and explore further details, please visit the above.</p>
        </div>
    );
}