import React from 'react'
import Head from 'next/head'
import Link from 'next/link'

const PrivacyPolicy = () => {
    return (
        <>
            <>
                <Head>
                    <title>Privacy Policy</title>
                    <meta name="description" content="Generated by create next app" />
                    <meta name="viewport" content="width=device-width, initial-scale=1" />
                </Head>
            </>
            <div className="container my-5 px-5 terms">
                <div className="pb-2">
                    <h1>Privacy Policy</h1>
                </div>
                <div>
                    <p>for Webfinex TechFusion Pvt Ltd. &amp; https://bluswap.co/</p>
                    <p>Effective Date: April 07, 2025</p>
                    <p>At&nbsp;<strong>Webfinex TechFusion Pvt.Ltd.</strong>, we value your privacy and are committed to protecting your personal data. This Privacy Policy outlines our practices concerning the collection, storage, use, processing, and disclosure of your personal data when you access our website &ldquo;<strong>https://bluswap.co/</strong>&rdquo; (&ldquo;Website&rdquo;) and utilise the services available on our platform (&ldquo;Services&rdquo;).</p>
                    <p>By using our Website and Services, you consent to the collection, storage, use, and disclosure of your personal data as described in this Policy. Please read this Privacy Policy carefully to understand how we treat your personal data. This policy sets out the basis on which any personal data we collect from you or you provide to us will be processed by us.</p>
                    <p>This Privacy Policy, referred to as the &ldquo;Policy,&rdquo; delineates the nature of the &ldquo;Personal Data&rdquo; we gather from you, our utilisation of it, how we share it, your rights and preferences, and how you can reach out to us regarding our privacy procedures. Additionally, this Policy outlines your data subject rights, including your ability to object to certain uses of your Personal Data by us.&nbsp;</p>
                    <p><strong>1. Data Handling Principles:</strong></p>
                    <p>a) Protection: We are dedicated to safeguarding user data and preventing accidental data disclosure.</p>
                    <p>b) Best Practices: We follow industry-standard data protection practices and regularly audit our systems through trusted third parties.</p>
                    <p><strong>2. Personal Data We Collect:</strong></p>
                    <p>a) Identity Data: Information such as your name, username, gender, and passwords.</p>
                    <p>b) Contact Data: Includes email addresses, phone numbers, and social media information.</p>
                    <p>c) KYC Data: Government-issued documents like Aadhaar, PAN Card, Voter ID, etc.</p>
                    <p>d) Financial Data: Transaction details, including Services availed and payments made through the Website.</p>
                    <p>e) Device Data: Information about your device, such as IP addresses, browser type, operating systems, and device information.</p>
                    <p>f) Usage Data: Information on how you use our Services.</p>
                    <p><strong>3. How Your Personal Data is Collected:</strong></p>
                    <p>We have ensured that the information on the Website is accurate and authentic. You agree to provide true, correct, and accurate information, and we are not responsible for any false or incorrect data you provide.</p>
                    <p>You can review and modify the information you&rsquo;ve provided during your Website usage. For any corrections, please contact us (details in Section 9).</p>
                    <p><strong>4. How We Use Your Personal Data:</strong></p>
                    <p>We use your data in compliance with the law, primarily to provide you with our Services and fulfil legal obligations.</p>
                    <p>By using our Services, you authorise us and our partners to contact you through various means to ensure you are aware of our Services&rsquo; features.</p>
                    <p>We may collect and share your information for purposes like storage, data analytics, consulting, legal requirements, or audit purposes with our subsidiaries, affiliates, or holding companies.</p>
                    <p><strong>5. Data Security:</strong></p>
                    <p>We employ security measures including encryption and firewalls to protect your data. However, you acknowledge that these measures do not guarantee absolute protection, and you assume all risks associated with data disclosure.</p>
                    <p><strong>6. Data Retention:</strong></p>
                    <p>Your personal data will be stored for a reasonable period after you cease using our Services.</p>
                    <p><strong>7. Business Transitions:</strong></p>
                    <p>In case of business transitions like mergers, acquisitions, or asset sales, your personal data may be transferred.</p>
                    <p><strong>8. Change in Privacy Policy:</strong></p>
                    <p>This Policy may change at our discretion. Any updates will be posted on our Website, and we may notify you through email. Continued use of our Services implies acceptance of these changes.</p>
                    <p><strong>9. Contact Us :</strong></p>
                    <p>For any questions or concerns regarding this Policy or your personal data, you can contact us at&nbsp;support@bluswap.co.&nbsp;</p>
                    <p>By using https://bluswap.co/, you agree to the terms of this Privacy Policy and the processing of your data as described herein. We are committed to protecting your privacy and maintaining the highest standards of data security.</p>
                </div>
            </div>
        </>
    )
}

export default PrivacyPolicy;
