import React from 'react'
import Head from 'next/head'
import Link from 'next/link'

const RefundPolicy = () => {
    return (
        <>
            <>
                <Head>
                    <title>Cancellation And Refund Policy</title>
                    <meta name="description" content="Generated by create next app" />
                    <meta name="viewport" content="width=device-width, initial-scale=1" />
                </Head>
            </>
            <div className="container my-5 px-5 terms">
                <div>
                    <h1>Cancellation and Refund Policy</h1>
                </div>
                <div>
                    <p>For bluSwap, A WebFinex TechFusion Brand</p>
                    <p>Effective Date:  April, 2025</p>
                    <p>Welcome to&nbsp;<strong>bluSwap</strong>, your trusted Third-Party Service Provider (TPSP) and Payment Service Provider and Payment Marketplace. This Cancellation and Refund Policy is designed to ensure a transparent and fair process for all transactions conducted on our platform. It outlines the conditions under which cancellations and refunds are permitted and the procedures to follow when either is desired.</p>
                    <h3>Definitions</h3>
                    <ul>
                        <li><strong>Third-Party Service Provider (TPSP):</strong>&nbsp;A service offering online payment solutions, facilitating transactions between customers and merchants.</li>
                        <li><strong>Payment Marketplace:</strong>&nbsp;An online platform that connects buyers and sellers, enabling them to conduct transactions.</li>
                        <li><strong>Customer:</strong>&nbsp;An individual or entity purchasing goods or services through bluSwap.</li>
                        <li><strong>Merchant:</strong>&nbsp;An individual or entity offering goods or services for sale on bluSwap.</li>
                        <li><strong>Refund:</strong>&nbsp;A return of funds to a customer for an undelivered or unsatisfactory product or service.</li>
                        <li><strong>Cancellation:</strong>&nbsp;The process of stopping a transaction or order before it is completed or fulfilled.</li>
                    </ul>
                    <h3>Cancellation Policy</h3>
                    <h4>Customer-Initiated Cancellations</h4>
                    <p>Customers can cancel transactions within 24 hours of placement, provided the transaction has not yet been processed or dispatched by the merchant. To cancel, please contact our support team with your order details.</p>
                    <h4>Merchant-Initiated Cancellations</h4>
                    <p>Merchants reserve the right to cancel transactions if they cannot fulfill the order due to stock issues or other unforeseen circumstances. Customers will be notified immediately and offered a refund or alternative solutions.</p>
                    <ol>
                        <li><strong>Service Cancellation:</strong>
                            <ul>
                                <li>Merchants may cancel their service subscription with bluSwap PSP at any time. To initiate a cancellation, the merchant must submit a written notice to bluSwap PSP&rsquo;s support team at least 30 days prior to the desired cancellation date.</li>
                                <li>Upon receiving a cancellation request, bluSwap PSP will process the cancellation effective the end of the billing cycle following the 30-day notice period.</li>
                            </ul>
                        </li>
                        <li><strong>Account Deactivation:</strong>
                            <ul>
                                <li>In the event of account deactivation by the merchant, any outstanding fees or charges must be settled prior to the deactivation becoming effective.</li>
                                <li>bluSwap PSP reserves the right to deactivate a merchant account due to non-compliance with our terms of service, regulatory requirements, or payment of fees.</li>
                            </ul>
                        </li>
                    </ol>
                    <h4>Platform-Initiated Cancellations</h4>
                    <p>bluSwap may cancel transactions under circumstances of fraud detection, non-compliance with our terms of service, or payment processing errors. Affected parties will be informed promptly.</p>
                    <h3>Refund Policy</h3>
                    <ol>
                        <li><strong>Service Subscription Fees:</strong>
                            <ul>
                                <li>bluSwap PSP offers a prorated refund for the unused portion of the service subscription, provided the cancellation request is made within the first 30 days of the service term. After 30 days, merchants are not eligible for a refund but may discontinue their services without incurring additional charges beyond the current billing cycle.</li>
                            </ul>
                        </li>
                        <li><strong>Transaction Fees:</strong>
                            <ul>
                                <li>Transaction fees incurred prior to the cancellation request are non-refundable as they are applied to costs associated with processing payments.</li>
                            </ul>
                        </li>
                        <li><strong>Special Circumstances:</strong>
                            <ul>
                                <li>In cases of service dissatisfaction, merchants are encouraged to contact bluSwap PSP&rsquo;s support team to discuss potential resolutions. Refunds in such scenarios will be considered on a case-by-case basis.</li>
                            </ul>
                        </li>
                        <li><strong>Refund Process:</strong>
                            <ul>
                                <li>Eligible refunds will be processed to the original payment method used by the merchant. Please allow up to 10 business days for the refund to be reflected in your account.</li>
                            </ul>
                        </li>
                    </ol>
                    <p><strong>Eligibility Criteria</strong></p>
                    <p>Refunds are processed based on the following criteria:</p>
                    <ul>
                        <li>Non-delivery of goods or services</li>
                        <li>Misrepresentation of item details</li>
                        <li>Defective goods or services</li>
                    </ul>
                    <p><strong>Refund Process</strong></p>
                    <p>To request a refund, customers must contact bluSwap support within 30 days of the transaction with order details and the reason for the refund request. We will process valid requests within 7-10 business days, issuing refunds to the original payment method.</p>
                    <p><strong>Special Considerations</strong></p>
                    <p>For digital goods or services, refunds are contingent upon proof that the item was not as described or was not accessible. Currency exchange rates at the time of refund will apply to transactions in foreign currencies.</p>
                    <h3>Dispute Resolution</h3>
                    <p>Disputes should be directed to our support team, who will mediate between the customer and the merchant. We aim to resolve disputes amicably within 14 business days.</p>
                    <h3>Amendments to the Policy</h3>
                    <p>bluSwap reserves the right to update this policy as necessary to reflect changes in our operations or legal requirements. Users will be notified of significant changes through our website or via email.</p>
                    <h3>Contact Information</h3>
                    <p>For any inquiries or further clarification on our Cancellation and Refund Policy, please contact our support team at&nbsp;<a>support@bluswap.co</a>&nbsp;I WhatsApp at 8296210723</p>
                </div>
            </div>
        </>
    )
}

export default RefundPolicy;