import React from 'react'
import Head from 'next/head'
import Link from 'next/link'
const TermsOfService = () => {
    return (
        <>
            <>
                <Head>
                    <title>Terms of Services</title>
                    <meta name="description" content="Generated by create next app" />
                    <meta name="viewport" content="width=device-width, initial-scale=1" />
                </Head>
            </>
            <div className="container my-5 px-5 terms">
                <div className="pb-2">
                    <h1>Terms of Service</h1>
                </div>
                <div>
                    <p>Terms of Service / Use for&nbsp;<strong>bluSwap</strong></p>
                    <p>(A WebFinex TechFusion Brand)</p>
                    <p>Terms &amp; Conditions&nbsp;</p>
                    <p>Updated on April 07, 2025</p>
                    <p>Welcome to&nbsp;<strong>bluSwap,</strong>&nbsp;Your Fintech Frontier</p>
                    <p>We offer financial infrastructure services for the internet. Individuals utilize our services to facilitate their online purchases, while businesses of all scales leverage our technology and solutions to accept payments, facilitate payouts, and efficiently manage their online operations. bluSwap is committed to providing transparency regarding our handling of the Personal Data you entrust to us.</p>
                    <p>&ldquo;Services&rdquo; encompasses the array of products and solutions specified by bluSwap in this Policy, which may encompass devices and applications provided by bluSwap. Our &ldquo;Business Services&rdquo; pertain to the services delivered by bluSwap to entities, hereinafter referred to as &ldquo;Business Users,&rdquo; who furnish us with &ldquo;End Customer&rdquo; Personal Data, both directly and indirectly, in the course of their own business operations and endeavours. Meanwhile, our &ldquo;End User Services&rdquo; encompass the services offered by bluSwap directly to individuals (as opposed to entities) for their personal use.</p>
                    <p>The term &ldquo;Sites&rdquo; encompasses bluSwap.co along with other websites, applications, and online services designated by bluSwap as governed by this Policy. Taken together, we use the term &ldquo;Services&rdquo; to collectively refer to Sites, Business Services, and End User Services.</p>
                    <p><strong>Access Keys</strong>&nbsp;</p>
                    <p>These shall refer to any confidential or secret keys, including but not limited to developer ID, certificate ID, application ID, username, and/or password, which are required by the Customer for accessing the Services in either a staging or production environment.</p>
                    <p><strong>API or Application Program Interface</strong>&nbsp;This term encompasses&nbsp;</p>
                    <p>(a) those components of the Application Program Interface made accessible to the Customer by the Service Provider under the terms of the Agreement, and&nbsp;</p>
                    <p>(b) API Documentation, which includes all documentation, data, and other supporting materials provided by the Service Provider to the Customer, either through Decentro or by any other means, for the purpose of utilising the API.</p>
                    <p><strong>Applicable Laws</strong>&nbsp;</p>
                    <p>Refers to all laws in force at the time of the Agreement&rsquo;s execution and during its term, which are applicable to the Parties involved.</p>
                    <p><strong>API Success</strong>&nbsp;</p>
                    <p>Denotes a &lsquo;success&rsquo; status code within the response fields for any of the API calls conducted during the provision of the Service.</p>
                    <p><strong>Person</strong></p>
                    <p>This encompasses any natural person, limited or unlimited liability company, corporation, partnership (whether limited or unlimited), proprietorship, Hindu undivided family, trust, union, association, government entity, or any other entity that may be legally recognized as a person.</p>
                    <p><strong>Regulatory Authority</strong></p>
                    <p>Refers to the relevant government agency responsible for overseeing the respective documents or authentication processes involved in the Services. This may include, but is not limited to, entities such as UIDAI, RBI, SEBI, IRDA, etc.</p>
                    <p><strong>Response Data</strong></p>
                    <p>Concerning transactions carried out by the Service Provider, this term signifies the &lsquo;success&rsquo; or similar status code in the case of a successful API response, accompanied by the &ldquo;Response Fields (if requested)&rdquo;. In cases of failure, the response data will include error details.</p>
                    <p><strong>Services</strong></p>
                    <p>Encompasses access to the APIs and bluSwap, as well as any other services explicitly mentioned in Annexure A of the Agreement, provided by the Service Provider to the Customer.</p>
                    <p><strong>Subscription Plan</strong>&nbsp;</p>
                    <p>The pricing, features, and options available within bluSwap Services depend on the specific Subscription Plan chosen by the Customer. This includes any usage or overage fees. bluSwap does not guarantee the continuous availability of a particular Subscription Plan. We retain the right to modify the prices, features, or options associated with a specific Subscription Plan without prior notice. However, such changes will not take effect until the commencement of your subsequent subscription term.</p>
                    <p><strong>Recurring Charges and Upgrades</strong></p>
                    <p>By subscribing to a Subscription Plan, the Customer grants bluSwap the authority to periodically charge the Customer&rsquo;s chosen payment method (e.g., monthly, quarterly, or annually, based on the selected Subscription Plan) without requiring an invoice. The Customer explicitly authorised bluSwap to charge the payment method, such as a credit card, for the relevant subscription charges, any usage or overage fees, as well as any applicable taxes and fees. This authorization remains effective until the conclusion of the Subscription Term and any subsequent Renewal Term, or until the Customer cancels all of its subscriptions.</p>
                    <p><strong>Upgrades</strong></p>
                    <p>In instances where the Customer exceeds the usage limits specified in their subscription plan, they will be automatically upgraded to the next higher Subscription Plan. The Customer acknowledges and agrees that they are responsible for covering the costs associated with the upgraded Subscription Plan. All fees and charges related to upgrades are non-refundable, even if the Customer did not fully utilise the allotted usage of the corresponding Subscription Plan.</p>
                    <p><strong>Taxes</strong></p>
                    <p>bluSwap&rsquo;s fees do not include taxes. The Customer is responsible for paying any applicable GST, sales tax, use tax, VAT, excise tax, withholding tax, or similar taxes or levies, whether domestic or foreign, except for taxes based on bluSwap&rsquo;s income. The Customer shall not deduct any taxes from payments made to bluSwap, unless required by law. If such deductions are mandated by law, the Customer shall adjust the payment amount accordingly to ensure that bluSwap receives an amount equal to what it would have received had no deductions or withholdings been applied, thereby absolving bluSwap from any related liabilities.</p>
                    <p><strong>Auto-renewals and Trials</strong>&nbsp;</p>
                    <p>If your account is set to auto-renewal or is in a trial period, and you have provided bluSwap with a payment method for the services, bluSwap may automatically charge your payment method at the end of the trial period or for the renewal. You can notify bluSwap if you wish to cancel your subscription.</p>
                    <p><strong>Purchase Orders</strong>&nbsp;</p>
                    <p>The Customer agrees to fulfil all payment obligations without necessitating the use of purchase orders or references to purchase order numbers. If a purchase order is deemed necessary, the Customer shall promptly notify bluSwap at least thirty (30) days prior to such requirement, and the parties will cooperate in establishing a billing process that incorporates these purchase order references. The Customer acknowledges that any purchase orders serve administrative purposes only, and any non-administrative terms (including legal, security, privacy, or financial terms) contained within purchase orders do not apply to the Customer&rsquo;s purchase or utilisation of bluSwap services.</p>
                    <p><strong>Modifications to the Policy</strong></p>
                    <p>bluSwap reserves the right to modify this Cancellation and Refund Policy at any time. Any changes will be effective immediately upon posting on our website. Customers are encouraged to review the policy periodically to stay informed of their rights and obligations.</p>
                    <p><strong>No Refunds</strong>&nbsp;</p>
                    <p>Subscription fees, usage fees, overage fees, and any other fees related to services, including higher subscription fees for upgrades, are non-refundable and non-creditable unless otherwise mandated by law. bluSwap subscriptions can be cancelled, with such cancellations taking effect at the conclusion of the then-current subscription term. Following cancellation, the Customer will be downgraded to a free plan, resulting in the loss of subscription features and functionality. In cases where the Customer fails to make timely payments for their subscriptions, bluSwap reserves the right to suspend or remove subscription features.</p>
                    <p><strong>Free Access Subscriptions</strong>&nbsp;</p>
                    <p>bluSwap may offer the Customer a bluSwap Service for free or on a trial basis (referred to as &ldquo;Free Access Subscriptions&rdquo;) or provide access to &ldquo;alpha,&rdquo; &ldquo;beta,&rdquo; or other early-stage bluSwap Services, integrations, or features (collectively termed as &ldquo;Beta Releases&rdquo;). These provisions apply to Free Access Subscriptions or Beta Releases, even if the latter are offered for a fee or count towards the Customer&rsquo;s Subscription Plan. bluSwap may make good faith efforts, at its discretion, to assist the Customer with Free Access Subscriptions or Beta Releases. However, and without limiting other disclaimers and limitations outlined in these Terms, the Customer acknowledges that Free Access Subscriptions and Beta Releases are provided on an &ldquo;as is&rdquo; and &ldquo;as available&rdquo; basis, without any warranties, support, maintenance, storage, service level agreements, or indemnity obligations. Consequently, any use of Beta Releases is at the Customer&rsquo;s sole risk. bluSwap does not guarantee the future release of Beta Releases or their availability under the same commercial or other terms. bluSwap reserves the right to terminate the Customer&rsquo;s access to any Free Access Subscriptions or Beta Releases at its discretion, without liability, for any reason or no reason.</p>
                    <p><strong>Online Terms</strong></p>
                    <p>By agreeing to these Terms of Service, you represent that you are at least the age of majority in your state or province of residence, or that you are the age of majority in your state or province of residence and you have given us your consent to allow any of your minor dependents to use this site.<br /><br />You may not use our products for any illegal or unauthorised purpose nor may you, in the use of the Service, violate any laws in your jurisdiction (including but not limited to copyright laws).<br /><br />You must not transmit any worms or viruses or any code of a destructive nature.<br /><br />A breach or violation of any of the Terms will result in an immediate termination of your Services.</p>
                    <p><strong>General Conditions</strong></p>
                    <p>You understand that your content (not including credit card information), may be transferred unencrypted and involve (a) transmissions over various networks; and (b) changes to conform and adapt to technical requirements of connecting networks or devices.&nbsp;</p>
                    <p>You agree not to reproduce, duplicate, copy, sell, resell or exploit any portion of the Service, use of the Service, or access to the Service or any contact on the website through which the service is provided, without express written permission by us.<br /><br />The headings used in this agreement are included for convenience only and will not limit or otherwise affect these Terms.</p>
                    <p><strong>Accuracy, Completeness and Timeliness of Information</strong></p>
                    <p>We are not responsible if information made available on this site is not accurate, complete or current. The material on this site is provided for general information only and should not be relied upon or used as the sole basis for making decisions without consulting primary, more accurate, more complete or more timely sources of information. Any reliance on the material on this site is at your own risk.</p>
                    <p><strong>Modifications to the Service and Prices</strong><br />We reserve the right at any time to modify or discontinue the Service (or any part or content thereof) without notice at any time.<br /><br />We shall not be liable to you or to any third-party for any modification, price change, suspension or discontinuance of the Service.<br /><br /><strong>Product or Services (if applicable)</strong></p>
                    <p>We have made every effort to display as accurately as possible the colours and images of our products that appear at the store. We cannot guarantee that your computer monitor&rsquo;s display of any colour will be accurate.<br />We reserve the right, but are not obligated, to limit the sales of our products or Services to any person, geographic region or jurisdiction. We may exercise this right on a case-by-case basis. We reserve the right to limit the quantities of any products or Services that we offer. All descriptions of products or product pricing are subject to change at any time without notice, at the sole discretion of us. We reserve the right to discontinue any product at any time. Any offer for any product or service made on this site is void where prohibited.</p>
                    <p><strong>Optional Tools</strong></p>
                    <p>You acknowledge and agree that we provide access to such tools &rdquo;as is&rdquo; and &ldquo;as available&rdquo; without any warranties, representations or conditions of any kind and without any endorsement. We shall have no liability whatsoever arising from or relating to your use of optional third-party tools.<br /><br />Any use by you of the optional tools offered through the site is entirely at your own risk and discretion and you should ensure that you are familiar with and approve of the terms on which tools are provided by the relevant third-party provider(s).<br /><br />We may also, in the future, offer new Services and/or features through the website (including, the release of new tools and resources). Such new features and/or Services shall also be subject to these Terms of Service.</p>
                    <p><strong>Personal Information</strong></p>
                    <p>Your submission of personal information through the store is governed by our Privacy Policy. To view our Privacy Policy, please see&nbsp;<Link href="">POLICY</Link></p>
                    <p><strong>Prohibited Uses</strong></p>
                    <p>Apart from the other restrictions stated in the Terms of Service, your use of the site or its content is expressly prohibited for the following purposes:</p>
                    <p>(a) Engaging in any unlawful activities.</p>
                    <p>(b) Encouraging or soliciting others to participate in any unlawful actions.</p>
                    <p>(c) Violating any international, federal, provincial, or state regulations, rules, laws, or local ordinances.</p>
                    <p>(d) Infringing upon or violating either our intellectual property rights or the intellectual property rights of others.</p>
                    <p>(e) Engaging in actions that involve harassment, abuse, insult, harm, defamation, slander, disparagement, intimidation, or discrimination based on factors such as gender, sexual orientation, religion, ethnicity, race, age, national origin, or disability.</p>
                    <p>(f) Providing false or misleading information.</p>
                    <p>(g) Uploading or transmitting viruses or any other type of malicious code that may disrupt the functionality or operation of the Service or any related website, other websites, or the Internet.</p>
                    <p>(h) Collecting or tracking the personal information of others.</p>
                    <p>(i) Engaging in spamming, phishing, data mining, pretexting, spidering, crawling, or scraping.</p>
                    <p>(j) Using the Service for any obscene or immoral purposes.</p>
                    <p>(k) Attempting to interfere with or circumvent the security features of the Service or any related website, other websites, or the Internet.</p>
                    <p>We reserve the right to terminate your use of the Service or any related website if you engage in any of the prohibited activities.</p>
                    <p>Customer&rsquo;s Approved Use Cases</p>
                    <p>The Customer agrees to adhere strictly to the specified use cases mentioned at the time of registration and shall not alter or add new use cases without prior approval from bluSwap. For clarification, the Customer is expressly prohibited from engaging in the following use cases at any time (Blacklisted Categories):</p>
                    <ul>
                        <li>Speculative Gaming</li>
                        <li>Gambling</li>
                        <li>Chit funds</li>
                        <li>Casino</li>
                        <li>Multi Level Marketing</li>
                        <li>Ponzi schemes</li>
                        <li>Spa</li>
                        <li>Escort Services</li>
                        <li>Friendship Clubs</li>
                        <li>Network Marketing</li>
                        <li>Lottery</li>
                        <li>Equity crowd funding</li>
                        <li>Any other speculative activities</li>
                    </ul>
                    <p><strong>Unauthorised Access</strong></p>
                    <p>The Service Provider shall hold harmless and indemnify the Customer against any claims, damages, losses, or expenses arising from or connected with any actions taken by a contractor, sub-contractor, or an employee of the Service Provider. These actions may result in or be intended by such contractor, sub-contractor, or employee to result in unauthorized access to any of the Customer&rsquo;s systems, data, or Confidential Information.&nbsp;</p>
                    <p>The incidents covered by this indemnity are by no means meant to diminish the &ldquo;Service Provider&rsquo;s&rdquo; responsibility to undertake all necessary measures to prevent the unauthorized use of Customer&rsquo;s proprietary information by its contractors, sub-contractors, or employees and, as such, restrict access to Customer&rsquo;s systems, data, and confidential information.&nbsp;</p>
                    <p>Irrespective of the contents of the Agreement, it is mutually agreed that the extent of this indemnification under any circumstances shall not surpass the total invoiced value of the Service Provider for that specific calendar month.</p>
                    <p><strong>Limitation Of Liability</strong><br />In no situation shall the Service Provider, its affiliates, its licensors, or any of their agents, employees, officers, directors, corporate partners, or participants bear responsibility for any direct, indirect, incidental, consequential, special, or exemplary damages experienced by the Customer and/or its end-users as a result of the services rendered by the Customer to its end-users, even if they were made aware of the potential for such damages.</p>
                    <p><strong>Indemnification</strong></p>
                    <p>The Customer agrees not to hold the Service Provider, its affiliates, licensors, or any of their respective parties, agents, employees, officers, directors, corporate partners, or participants responsible for any damages, legal actions, claims, and/or disputes (referred to collectively as &ldquo;liabilities&rdquo;), whether currently known or unknown, that have arisen or may arise in connection with the Customer&rsquo;s actions. This includes, but is not limited to, any liabilities arising from interactions with end-users, disputes with end-users, guidance, advice, actions, or services provided by the Customer or its affiliates or licensors, as well as any loss or destruction of the Customer&rsquo;s data.</p>
                    <p><strong>Severability</strong></p>
                    <p>In the event that any provision of these Terms of Service is determined to be unlawful, void or unenforceable, such provision shall nonetheless be enforceable to the fullest extent permitted by applicable law, and the unenforceable portion shall be deemed to be severed from these Terms of Service, such determination shall not affect the validity and enforceability of any other remaining provisions.</p>
                    <p><strong>Termination</strong></p>
                    <p>The obligations and liabilities of the parties incurred prior to the termination date shall survive the termination of this agreement for all purposes.<br />These Terms of Service are effective unless and until terminated by either you or us. You may terminate these Terms of Service at any time by notifying us that you no longer wish to use our Services, or when you cease using our site.<br />If in our sole judgement you fail, or we suspect that you have failed, to comply with any term or provision of these Terms of Service, we also may terminate this agreement at any time without notice and you will remain liable for all amounts due up to and including the date of termination; and/or accordingly may deny you access to our Services (or any part thereof).</p>
                    <p><strong>Entire Agreement</strong></p>
                    <p>The failure of us to exercise or enforce any right or provision of these Terms of Service shall not constitute a waiver of such right or provision.<br />These Terms of Service and any policies or operating rules posted by us on this site or in respect to The Service constitutes the entire agreement and understanding between you and us and govern your use of the Service, superseding any prior or contemporaneous agreements, communications and proposals, whether oral or written, between you and us (including, but not limited to, any prior versions of the Terms of Service).<br />Any ambiguities in the interpretation of these Terms of Service shall not be construed against the drafting party.</p>
                    <p><strong>Governing Law</strong></p>
                    <p>These Terms of Service and any separate agreements whereby we provide you Services shall be governed by and construed in accordance with the laws of India.</p>
                    <p><strong>Changes to Terms and Service</strong></p>
                    <p>You can review the most current version of the Terms of Service at any time at this page.<br />We reserve the right, at our sole discretion, to update, change or replace any part of these Terms of Service by posting updates and changes to our website. It is your responsibility to check our website periodically for changes. Your continued use of or access to our website or the Service following the posting of any changes to these Terms of Service constitutes acceptance of those changes.</p>
                    <p><strong>Payment APIs</strong>&nbsp;</p>
                    <p>bluSwap shall not assume responsibility for any disagreements arising between the involved parties in a transaction, such as disputes regarding pricing, product quality, quantity, delivery, non-delivery, or delivery delays.</p>
                    <p>bluSwap also disclaims any liability arising from payment delays since payment processing is contingent on various entities, including acquiring financial institutions, Issuing &amp; Acquiring Bank processors, and other third parties.</p>
                    <p>With regard to &ldquo;Refunds / Chargebacks,&rdquo; bluSwap commits to transferring the Transaction Amount (deducting Permissible Deductions) to the Customer&rsquo;s settlement account within two (2) Nodal Bank Working Days following the completion date (T) of the Transaction, in accordance with the customer&rsquo;s defined terms.</p>
                    <p><strong>Payment</strong>&nbsp;<strong>Refunds / Chargebacks</strong></p>
                    <p>A chargeback refers to a transaction that is deemed uncollectible and is returned to the service provider, bluSwap, for a refund to the concerned payer due to any of the following circumstances:</p>
                    <ul>
                        <li>The merchant or payer refuses to honour a payment or requests a refund because the purchased products were not as described, defective, deficient, incomplete, or unsatisfactory for any reason, or when payment for the same product has already been made.</li>
                        <li>Any payment that has been returned by the acquiring bank.</li>
                        <li>Any unsuccessful transaction.</li>
                        <li>Any debit resulting from an alleged hacking breach of security or encryption methods utilised by the service provider, bluSwap, or the payee.</li>
                    </ul>
                    <p>Upon receiving a chargeback request from its banking partner, bluSwap reserves the specified amount in the merchant&rsquo;s master virtual account. Subsequently, bluSwap notifies the merchant to either approve or reject the chargeback, providing valid proof of service delivery. bluSwap then evaluates and either accepts or rejects the counter-claim, instructing the merchant to initiate a refund to the consumer. Following this process, bluSwap informs the banking partner accordingly. It&rsquo;s essential to note that bluSwap does not handle refund scenarios, as this is the responsibility of its merchants.</p>
                    <p>For any assistance, both merchants and customer can contact bluSwap via email at&nbsp;<Link href="mailto:support@bluswap.co">support@bluswap.co</Link>.</p>
                    <p>bluSwap will only make payments related to chargebacks once it has received the necessary funds from the relevant acquiring bank, service provider, payee, merchant, or marketplace. bluSwap holds no responsibility for claims, disputes, or penalties arising from such chargebacks and shall be indemnified against any such claims. Upon receiving the chargeback amount from the acquiring bank or service provider, bluSwap will transfer the received amount to the merchant, marketplace, or payer within 7 days.</p>
                    <p>In the event that the involved parties have agreed that the merchant, marketplace, or payer is entitled to a chargeback for any transaction, bluSwap may, at its discretion, implement this chargeback entitlement through one or more of the following methods:</p>
                    <ol>
                        <li>Deducting the relevant amount, or a portion thereof, from any payments to the payee.</li>
                        <li>Billing the concerned party for the relevant amount, or a portion thereof.</li>
                    </ol>
                    <p><strong>Contact Information</strong></p>
                    <p>Questions about the Terms of Service should be sent to us at&nbsp;support@bluSwap.co</p>
                    <p>bluSwap.co</p>
                    <p>WhatsApp: +91-8296210723</p>
                    <p>bluswap.psps@gmail.com</p>
                    <p>This comprehensive set of terms and conditions outlines the rights, responsibilities, and procedures governing the use of bluSwap&rsquo;s FastFlow Pay services. Customers are encouraged to review and understand these terms.</p>
                </div>

            </div>
        </>
    )
}

export default TermsOfService;