/* eslint-disable @next/next/no-img-element */
import React from 'react'
import Head from 'next/head'
import Link from 'next/link'
import { useState } from 'react'
import Image from 'next/image'


export default function Blogs() {
  const [blogs, setBlogs] = useState([{
    id: 1,
    title: "Sessions 2023: Powering growth for the internet economy",
    description: "More than 250,000 companies now use Stripe's revenue and finance tools, and our automated revenue recovery features earned businesses an extra $3.8 billion in 2022.",
    metaTitle: "Powering growth for the internet economy – bluSwap",
    metaDescription: "More than 250,000 companies now use Stripe's revenue and finance tools, and our automated revenue recovery features earned businesses an extra $3.8 billion in 2022.",
    metaKeywords: "bluSwap, bluSwap blogs, Fintech solutions, payment solution, Fintech, bluSwap&#39;s Fintech, Payment Industry Future, What is Fintech, Future of fintech, Future of Payment Industry, AI in Payment processing.",
    canonicalURL: "https://bluswap.co/blog/sessions-2023-powering-growth-for-the-internet-economy",
    image: ""
  }, {
    id: 2,
    title: "What is fintech?",
    description: "More than 250,000 companies now use Stripe's revenue and finance tools, and our automated revenue recovery features earned businesses an extra $3.8 billion in 2022.",
    metaTitle: "What is fintech? - bluSwap",
    metaDescription: "Fintech's are companies that rely primarily on technology and cloud services and less so on physical locations to provide financial services to customers.",
    metaKeywords: "bluSwap, bluSwap blogs, Fintech, bluSwap's Fintech, What is Fintech, Future of fintech",
    canonicalURL: "https://www.mckinsey.com/featured-insights/mckinsey-explainers/what-is-fintech",
    image: "/assets/img/blogs/blog2.png"
  }, {
    id: 3,
    title: "The Evolution of the Payments Industry",
    description: "In the upcoming year, the payments industry will face elevated risk levels, heightened regulatory scrutiny, and substantial shifts in global standards.",
    metaTitle: "The Evolution of the Payments Industry - bluSwap",
    metaDescription: "Fintech's are companies that rely primarily on technology and cloud services and less so on physical locations to provide financial services to customers.",
    metaKeywords: "bluSwap's Fintech, Fintech,Future of Payment Industry, Payment Industry Future",
    canonicalURL: "https://www.mckinsey.com/featured-insights/mckinsey-explainers/what-is-fintech",
    image: "/assets/img/blogs/blog3.png"
  }])

  // Function to format title for URL - replace spaces with hyphens and remove special characters
  const formatTitleForURL = (title) => {
    return title
      .toLowerCase()
      .replace(/[^a-z0-9\s-]/g, '') // Remove special characters except spaces and hyphens
      .replace(/\s+/g, '-')         // Replace spaces with hyphens
      .replace(/-+/g, '-')          // Replace multiple hyphens with a single hyphen
      .trim();                      // Remove leading/trailing spaces
  };

  // href={`/blogs/${formatTitleForURL(item.title)}`}


  return (
    <>
      <Head>
        <title>Blogs</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <>
        <main>
          <div className="main-section">
            <div className="container">
              <div className="row pt-5">
                <div className="col-md-6 order-2 order-md-1">
                  <div className="blog-title">
                    <h1>The Future of AI in Payment Processing</h1>
                    <p>Transforming Transactions with Intelligent Solutions</p>
                  </div>
                  <div className="read-more-btn">
                    <button>
                      <Link href="/blogs/details/">Read More</Link>
                    </button>
                  </div>
                </div>
                <div className="col-md-6 order-1 order-md-2">
                  <div className="blog-main-img">
                    <Image src="assets/img/blog-main.svg" alt="" width={500} height={500} className='w-100 h-auto' />
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div className="container">
            <div className="sliders">
              <div className="row py-5 my-md-5">
                {
                  blogs.map((item) => (
                    <div className="col-md-4 mb-4" key={item.id} style={{ overflow: "hidden" }}>
                      <div className="blog-box" style={{
                        height: '90%', display: 'flex', flexDirection: 'column', border: 'none', boxShadow: '0 4px 15px rgba(0, 0, 0, 0.08)',
                        border: 'none',
                        background: '#fff',
                        borderRadius: '25px',
                        padding: '15px',
                      }}>

                        <Link href="/blogs" style={{ display: 'flex', flexDirection: 'column', height: '100%' }}>
                          <div className="blog-img" style={{ height: '200px', overflow: 'hidden', position: 'relative' }}>
                            {item.image ? (
                              <Image
                                src={item.image && item.image}
                                alt={item.title}
                                height={200}
                                width={200}
                                style={{
                                  borderRadius: "22px",
                                  width: '100%',
                                  height: '100%',
                                  objectFit: 'cover',
                                  position: 'absolute',
                                  top: 0,
                                  left: 0
                                }}
                              />
                            ) : (
                              <div style={{
                                width: '100%',
                                height: '100%',
                                backgroundColor: '#f0f0f0',
                                display: 'flex',
                                alignItems: 'center',
                                justifyContent: 'center',
                                borderRadius: "22px"
                              }}>
                                <span>No Image</span>
                              </div>
                            )}
                          </div>
                          <div className="blog-discrption" style={{ flex: 1, display: 'flex', flexDirection: 'column' }}>
                            <span>Fintech</span>
                            <h3 style={{
                              overflow: 'hidden',
                              textOverflow: 'ellipsis',
                              display: '-webkit-box',
                              WebkitLineClamp: 2,
                              WebkitBoxOrient: 'vertical',
                              minHeight: '48px'
                            }}>
                              {item.title}
                            </h3>
                            <p style={{
                              flex: 1,
                              overflow: 'hidden',
                              textOverflow: 'ellipsis',
                              display: '-webkit-box',
                              WebkitLineClamp: 3,
                              WebkitBoxOrient: 'vertical',
                              minHeight: '60px'
                            }}>
                              {item.description}
                            </p>
                            <div style={{ marginTop: 'auto' }}>
                              <Image src="/assets/img/svg/arrow.png" alt="Read more" className='img-fluid' height={20} width={20} />
                            </div>
                          </div>
                        </Link>
                      </div>
                    </div>
                  ))
                }
              </div>
            </div>
          </div>
        </main>
      </>
    </>
  )
}